name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Jest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout...
        uses: actions/checkout@v2

      - name: Loading Node...
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: Installing Modules...
        run: npm ci

      - name: Testing...
        run: npm test

      - name: Uploading results...
        uses: actions/upload-artifact@v2
        with:
          name: coverage-files
          path: coverage

  CodeCov:
    needs: Jest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout...
        uses: actions/checkout@v2

      - name: Downloading coverage files...
        uses: actions/download-artifact@v2
        with:
          name: coverage-files
          path: coverage

      - name: Uploading to CodeCov...
        uses: codecov/codecov-action@v1
        with:
          directory: coverage/
